driverDocType2Category:
  MOTO: A
  CAR: B
  TRUCK: C
  BUS: D

driverDocType2Categories:
  MOTO: A,A1,A2
  CAR: B,B1,B2
  TRUCK: C.C1,C2
  BUS: D,D1,D2

test_bean_map:
  beanOne: beanOne
  beanTwo: beanTwo

start.flag:
  true

start.date:

start.command.list:
  phone_on


start.check.date:
  24-08-2019
start.check:date_format:
  dd-MM-yyyy
